# Generated by Django 3.2.25 on 2024-06-18 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_rename_date_time_subtitle_end_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='local_path',
        ),
        migrations.AddField(
            model_name='video',
            name='s3_key',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
